# Minimal stubs for faster_whisper to satisfy mypy
# This is not a complete stub file, just enough to reduce mypy errors

from typing import Any, Optional, List, Dict, Iterator

class WhisperModel:
    def __init__(self, model_size_or_path: str, device: str = "auto", compute_type: str = "default", **kwargs) -> None: ...
    def transcribe(self, audio: str, language: Optional[str] = None, **kwargs) -> tuple[Iterator[Any], Any]: ...

class BatchedInferencePipeline:
    def __init__(self, model: WhisperModel) -> None: ...
    def transcribe(self, audio: str, language: Optional[str] = None, **kwargs) -> tuple[Iterator[Any], Any]: ...
